steps:
  # Step 0: Install pnpm, project dependencies, and build the app
  # We use bash to run multiple commands sequentially in the same container
  - name: 'node:latest' # Use a standard Node image
    entrypoint: 'bash' # Set the entrypoint to bash
    args:
      - '-c' # Tell bash to interpret the following string as a command
      - |
        npm install -g pnpm && \
        pnpm install && \
        pnpm run build
    dir: '.' # Specify your project's root directory if needed

  # Step 1: Deploy to Firebase Hosting
  # This step will use the build output created in Step 0
  # Make sure the --public flag points to the directory where 'pnpm run build' outputs files
  - name: 'gcr.io/word-rush-49a0d/firebase' # <-- This is the image name
    args: ['deploy', '--project=word-rush-49a0d', '--only=hosting', '--public=dist'] # Adjust 'dist'

# Keep the logging option
options:
  logging: CLOUD_LOGGING_ONLY
