steps:
  # Step 0: Install pnpm globally
  - name: 'node:latest' # Use the same Node image
    entrypoint: 'npm'
    args: ['install', '-g', 'pnpm']

  # Step 1: Install project dependencies using pnpm
  # This step now runs *after* pnpm has been installed globally in the previous step
  - name: 'node:latest' # Use the same Node image with pnpm now available
    entrypoint: 'pnpm'
    args: ['install']
    dir: '.' # Specify your project's root directory if needed

  # Step 2: Run the build script
  - name: 'node:latest' # Use the same or compatible Node image
    entrypoint: 'pnpm'
    args: ['run', 'build']
    dir: '.' # Specify your project's root directory if needed

  # Add this options block to specify logging behavior (already added, keeping it)
options:
  logging: CLOUD_LOGGING_ONLY
